In [1]:
a = input("Daal na yaaarrrrrrrrrrrrrrr:")

for i in range(1, int(a)+1):
    print(i)

1
2
3
4
5
6

In [2]:
a = 5
b = 8
c = 3

if a > b:
    if a > c:
        print(a)
    else:
        print(c)
elif c > b:
    print(c)
else:
    print(b)

8

In [3]:
a = [1,2, 54, 7, 54]
b = (346, 67, 978)

list(b), tuple(a)

([346, 67, 978], (1, 2, 54, 7, 54))

In [4]:
data = [
    {"Name": "Aditya", "Marks": -50},
    {"Name": "Lovesh", "Marks": 100},
]

In [5]:
import pandas as pd

df = pd.DataFrame(data)
df

     Name  Marks
0  Aditya    -50
1  Lovesh    100

In [6]:
df.to_csv("data/marks.csv")

In [7]:
df_read = pd.read_csv("data/marks.csv", index_col=[0, 1])
df_read

          Marks
  Name
0 Aditya    -50
1 Lovesh    100

In [8]:
df_read.loc[0:1]

          Marks
  Name
0 Aditya    -50
1 Lovesh    100